################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/adc_functions.c \
../src/bluetooth_utilities.c \
../src/bsp_trace.c \
../src/flash_functions.c \
../src/main.c \
../src/retargetio.c \
../src/retargetserial.c \
../src/spi_functions.c 

OBJS += \
./src/adc_functions.o \
./src/bluetooth_utilities.o \
./src/bsp_trace.o \
./src/flash_functions.o \
./src/main.o \
./src/retargetio.o \
./src/retargetserial.o \
./src/spi_functions.o 

C_DEPS += \
./src/adc_functions.d \
./src/bluetooth_utilities.d \
./src/bsp_trace.d \
./src/flash_functions.d \
./src/main.d \
./src/retargetio.d \
./src/retargetserial.d \
./src/spi_functions.d 


# Each subdirectory must supply rules for building sources it contributes
src/adc_functions.o: ../src/adc_functions.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DBGM111A256V2=1' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\uartdrv\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\halconfig\inc\hal-config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\app\bluetooth\common\util" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\bootloader\api" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\drivers" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\radio\rail_lib\common" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\tempdrv\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\sleep\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Source" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\common\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Source\GCC" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\sleep\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emlib\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\BGM11_BRD4300A\config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emlib\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\bootloader" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\CMSIS\Include" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Include" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\tempdrv\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\module\config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\bsp" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"src/adc_functions.d" -MT"src/adc_functions.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/bluetooth_utilities.o: ../src/bluetooth_utilities.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DBGM111A256V2=1' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\uartdrv\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\halconfig\inc\hal-config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\app\bluetooth\common\util" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\bootloader\api" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\drivers" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\radio\rail_lib\common" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\tempdrv\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\sleep\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Source" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\common\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Source\GCC" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\sleep\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emlib\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\BGM11_BRD4300A\config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emlib\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\bootloader" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\CMSIS\Include" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Include" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\tempdrv\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\module\config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\bsp" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"src/bluetooth_utilities.d" -MT"src/bluetooth_utilities.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/bsp_trace.o: ../src/bsp_trace.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DBGM111A256V2=1' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\uartdrv\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\halconfig\inc\hal-config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\app\bluetooth\common\util" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\bootloader\api" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\drivers" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\radio\rail_lib\common" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\tempdrv\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\sleep\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Source" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\common\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Source\GCC" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\sleep\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emlib\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\BGM11_BRD4300A\config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emlib\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\bootloader" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\CMSIS\Include" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Include" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\tempdrv\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\module\config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\bsp" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"src/bsp_trace.d" -MT"src/bsp_trace.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/flash_functions.o: ../src/flash_functions.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DBGM111A256V2=1' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\uartdrv\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\halconfig\inc\hal-config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\app\bluetooth\common\util" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\bootloader\api" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\drivers" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\radio\rail_lib\common" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\tempdrv\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\sleep\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Source" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\common\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Source\GCC" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\sleep\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emlib\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\BGM11_BRD4300A\config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emlib\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\bootloader" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\CMSIS\Include" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Include" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\tempdrv\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\module\config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\bsp" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"src/flash_functions.d" -MT"src/flash_functions.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/main.o: ../src/main.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DBGM111A256V2=1' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\uartdrv\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\halconfig\inc\hal-config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\app\bluetooth\common\util" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\bootloader\api" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\drivers" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\radio\rail_lib\common" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\tempdrv\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\sleep\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Source" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\common\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Source\GCC" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\sleep\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emlib\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\BGM11_BRD4300A\config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emlib\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\bootloader" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\CMSIS\Include" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Include" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\tempdrv\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\module\config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\bsp" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"src/main.d" -MT"src/main.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/retargetio.o: ../src/retargetio.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DBGM111A256V2=1' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\uartdrv\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\halconfig\inc\hal-config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\app\bluetooth\common\util" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\bootloader\api" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\drivers" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\radio\rail_lib\common" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\tempdrv\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\sleep\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Source" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\common\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Source\GCC" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\sleep\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emlib\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\BGM11_BRD4300A\config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emlib\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\bootloader" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\CMSIS\Include" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Include" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\tempdrv\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\module\config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\bsp" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"src/retargetio.d" -MT"src/retargetio.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/retargetserial.o: ../src/retargetserial.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DBGM111A256V2=1' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\uartdrv\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\halconfig\inc\hal-config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\app\bluetooth\common\util" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\bootloader\api" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\drivers" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\radio\rail_lib\common" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\tempdrv\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\sleep\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Source" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\common\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Source\GCC" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\sleep\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emlib\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\BGM11_BRD4300A\config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emlib\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\bootloader" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\CMSIS\Include" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Include" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\tempdrv\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\module\config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\bsp" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"src/retargetserial.d" -MT"src/retargetserial.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/spi_functions.o: ../src/spi_functions.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DBGM111A256V2=1' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\uartdrv\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\halconfig\inc\hal-config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\app\bluetooth\common\util" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\bootloader\api" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\drivers" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\radio\rail_lib\common" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\tempdrv\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\sleep\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Source" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\common\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Source\GCC" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\sleep\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emlib\src" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\BGM11_BRD4300A\config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emlib\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\bootloader" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\CMSIS\Include" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\Device\SiliconLabs\BGM1\Include" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\tempdrv\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\module\config" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\bsp" -I"C:\Users\Sam\SimplicityStudio\v4_workspace\SPI_dev\retry\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"src/spi_functions.d" -MT"src/spi_functions.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


